name: Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Publish file to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .
          target: ./myApp

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

      # - name: Deploy execute command ssh to remote server
      #   env:
      #      IMAGE_NAME: my-image:${{ github.sha }}
      #   uses: appleboy/ssh-action@master
      #   with:
      #    host: ${{ secrets.HOST }}
      #    username: ${{ secrets.USERNAME }}
      #    password: ${{ secrets.PASSWORD }}
      #    script: |
      #         docker build -f ./myApp/Dockerfile -t my-image:${{ github.sha }} .
      #         docker run -d -p 80:80 my-image:${{ github.sha }}
      #         docker ps -a
      - name: Deploy execute command ssh to remote server
        env:
           IMAGE_NAME: my-image:${{ github.sha }}
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
              docker-compose down
              docker-compose up -d -- build
              docker ps -a