name: Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Deploy to Azure VM
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy execute command ssh to remote server
        env:
           IMAGE_NAME: my-image:${{ github.sha }}
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-image:${{ github.sha }} .

      - name: Tag Docker image
        run: docker tag my-image:${{ github.sha }} my-image:latest

      - name: Save Docker image as tar archive
        run: docker save -o my-image.tar my-image:${{ github.sha }}

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: my-image.tar
          target: /myApp/my-image.tar

      - name: Load Docker image on Azure VM
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'docker load -i /myApp/my-image.tar'

  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

      - name: Copy files to Azure VM
        run: |
          scp -r ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/myApp

      - name: Deploy execute command ssh to remote server
        env:
           IMAGE_NAME: my-image:${{ github.sha }}
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
              docker ps -a