name: Azure VM Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Deploy to Azure VM
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build image and push Dockerfile
        uses: docker/build-push-action@v3
        with:
         file: ./Dockerfile
         context: .
         push: true
         tags: my-image:${{ github.sha }}

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 2m
          source: my-image.tar
          target: ./myApp/my-image.tar


      - name: Deploy execute command ssh to remote server & Load Docker image on Azure VM
        env:
           IMAGE_NAME: my-image:${{ github.sha }}
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'docker load -i ./myApp/my-image.tar'
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:

      - name: Publish file to Azure VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: .
          target: ./myApp

      - name: Deploy execute command ssh to remote server
        env:
           IMAGE_NAME: my-image:${{ github.sha }}
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
         script: |
              docker build -t my-image:${{ github.sha }} .
              docker run -d -p 80:8000 my-image:${{ github.sha }}
              docker images 
              docker ps -a
